"use client";

import { FormEvent, useState } from "react";

export function AuthScreen({ onComplete }: { onComplete: (user: { id: string; username: string }) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("signup");
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Request failed"); onComplete(payload.user); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } finally { setBusy(false); } }
  return <div className="auth-backdrop"><div className="auth-card"><section className="auth-copy"><div><div className="auth-badge">OPENVIEW / MARKET LAB</div><h1>See the market in your own frame.</h1><p>A serious charting workspace for curious traders: analysis tools, saved layouts, transparent data states, and a paper-trading league that keeps the stakes educational.</p></div><div className="mono muted" style={{ fontSize: 11 }}>No affiliation with TradingView · Open source foundation</div></section><form className="auth-form" onSubmit={submit}><div className="auth-tabs"><button type="button" className={mode === "signup" ? "active" : ""} onClick={() => { setMode("signup"); setError(""); }}>Create account</button><button type="button" className={mode === "login" ? "active" : ""} onClick={() => { setMode("login"); setError(""); }}>Log in</button></div><h2>{mode === "signup" ? "Open your workspace" : "Welcome back"}</h2><p>Username/password only. No email collection in this first release.</p><label className="field-label" htmlFor="username">Username</label><input id="username" className="field" autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} placeholder="your_handle" required /><label className="field-label" htmlFor="password">Password</label><input id="password" className="field" type="password" autoComplete={mode === "signup" ? "new-password" : "current-password"} value={password} onChange={e => setPassword(e.target.value)} placeholder="8+ characters" required /><button className="primary-btn" disabled={busy}>{busy ? "Connecting…" : mode === "signup" ? "Create account" : "Log in"}</button>{error && <div className="auth-error">{error}</div>}<div className="auth-note">Your paper account starts with $100,000 simulated cash. Real broker trading is intentionally not connected.</div></form></div></div>;
}
